name: experiments-binding-affinity
channels:
  - pytorch
  - conda-forge
  - defaults
  - omnia
dependencies:
  # Base depends
  - python
  - pip
  - pandas
  - requests
  - pint
  - appdirs
  - openforcefield >=0.8.1
  - tqdm
  - pytorch 1.6
  - torchvision
  - pytorch_geometric
  - pytorch-lightning
  - xgboost
  - watermark
  - papermill
  - jupyterlab
  - nglview
  - matplotlib-base


  - pip:
      - --find-links https://pytorch-geometric.com/whl/torch-1.6.0+cpu.html
      # PyTorch trees
      - https://github.com/ValentinFigue/Sklearn_PyTorch/archive/1b56a43e41de331ecdf73d08418f75bb34c9fa06.tar.gz
      # Torch geometric
      - torch_scatter
      - torch_sparse
      - torch_cluster
      - torch_spline_conv
### After creating the environment, you will need to run these this to enable jupyter-lab widgets
# jupyter labextension install @jupyter-widgets/jupyterlab-manager nglview-js-widgets @jupyterlab/toc