name: experiments-binding-affinity
channels:
  - pytorch
  - conda-forge
  - defaults
  - omnia
dependencies:
  # Base depends
  - python
  - pip
  - jupyterlab
  - pandas
  - requests
  - pint
  - appdirs
  - openforcefield
  - tqdm
  - pytorch 1.6
  - torchvision
  - xgboost
  - watermark
  #- cudatoolkit 10.2

  - pip:
      - --find-links https://pytorch-geometric.com/whl/torch-1.6.0.html
      # PyTorch trees
      - https://github.com/ValentinFigue/Sklearn_PyTorch/archive/1b56a43e41de331ecdf73d08418f75bb34c9fa06.tar.gz
      # Torch geometric
      - torch_scatter==latest+cpu
      - torch_sparse==latest+cpu
      - torch_cluster==latest+cpu
      - torch_spline_conv==latest+cpu
      - torch-geometric
### After creating the environment, you will need to run these two commands to override lastest OFF with a dev version
# conda remove --force openforcefield
# pip install --no-deps https://github.com/openforcefield/openforcefield/archive/toolkit-inheritance.zip
